### ISSUE TITLE
Inserting records with relating data

### ISSUE THREAD

**Issue by f1r3starter** [cristianpontes/zoho-crm-client-php#1]
There is a problem in an inserting records with something more complex, than simple associative array (Key => Value). 
For example, there is a need to insert invoice record with related products, the most obvious way  to do that, which comes to a head first, is to put related products to the subarray, like that:

```php
$invoices->insertRecords()->addRecord([
    'Subject' => 'Test Subject',
    'CONTACTID' => 423412341234,
    'Product Details' => [
        [
            'Product Id' => 314534523452345,
            'Product Name' => 'Test name',
            'Unit Price' => '4800.0',
            'Quantity' => '1.0',
            'Total' => '4800',
        ]
    ],
])->request();
```

 After executing Zoho CRM Client throws the next warning:

`PHP Warning:  It is not yet possible to assign complex types to properties in /var/www/zoho/vendor/cristianpontes/zoho-crm-client-php/CristianPontes/ZohoCRMClient/Transport/XmlDataTransportDecorator.php on line 76`

Is it possible to proceed related data to records?

**Comment by cristianpontes** [comment]
The nested values are supported now. Please check the documentation page in the insertRecords section. https://cristianpontes.github.io/zoho-crm-client-php/#insertRecords

**Comment by f1r3starter** [comment]
Thank you!
