### ISSUE TITLE
issue with getrelatedrecords

### ISSUE THREAD

**Issue by razaman2** [cristianpontes/zoho-crm-client-php#12]
i have been trying to use the getrelatedrecords function and cant get it to work with custom modules.

this exception is being thrown when i try.

<br />
<b>Fatal error</b>:  Uncaught CristianPontes\ZohoCRMClient\Exception\ZohoErrorException: Unable to populate data, please check if mandatory value is entered correctly. in /var/www/wsdl2php_generated/vendor/cristianpontes/zoho-crm-client-php/CristianPontes/ZohoCRMClient/Transport/XmlDataTransportDecorator.php:135
Stack trace:
#0 /var/www/wsdl2php_generated/vendor/cristianpontes/zoho-crm-client-php/CristianPontes/ZohoCRMClient/Transport/XmlDataTransportDecorator.php(49): CristianPontes\ZohoCRMClient\Transport\XmlDataTransportDecorator-&gt;parse('&lt;?xml version=&quot;...')
#1 /var/www/wsdl2php_generated/vendor/cristianpontes/zoho-crm-client-php/CristianPontes/ZohoCRMClient/Transport/TransportRequest.php(96): CristianPontes\ZohoCRMClient\Transport\XmlDataTransportDecorator-&gt;call('CustomModule2', 'getRelatedRecor...', Array)
#2 /var/www/wsdl2php_generated/vendor/cristianpontes/zoho-crm-client-php/CristianPontes/ZohoCRMClient/Request/GetRelatedRecords.php(84): CristianPontes\ZohoCRMClient\Transport\TransportRequest-&gt;request()
#3 /var/www/html/s in <b>/var/www/wsdl2php_generated/vendor/cristianpontes/zoho-crm-client-php/CristianPontes/ZohoCRMClient/Transport/XmlDataTransportDecorator.php</b> on line <b>135</b><br />

im calling this function in my code

public function testGetRelatedRecords()
		{
			$this->crm = $this->setCrm(new ZohoCRMClient("CustomModule2", $this->auth));

			$user = $this->crm->getRelatedRecords()
				->id($this->id)
				->parentModule("Potentials")
				->withEmptyFields()
				->request();

			return $user[1]->getData();
		}

the function above is making a call to a custom module in crm. whenever i call the method it throws the above exception. 

if i then make a call tho a non custommodule like contacts without changing anything in the function other than the module to call, it workes fine. 

below is a call to a non custommodule. this is the same method as the one above. the only difference is that its not calling a custom module.

public function testGetRelatedRecords()
		{
			$this->crm = $this->setCrm(new ZohoCRMClient("Contacts", $this->auth));

			$user = $this->crm->getRelatedRecords()
				->id($this->id)
				->parentModule("Potentials")
				->withEmptyFields()
				->request();

			return $user[1]->getData();
		}

**Comment by pikulsky** [comment]
in this forum post it's suggested to use getSearchRecordsByPDC for custom module:
https://forums.zoho.com/topic/getting-related-lists-for-custom-modules

**Comment by cristianpontes** [comment]
https://www.zoho.com/crm/help/api/getrelatedrecords.html#Request_Parameters
> The getRelatedRecords method does not support Custom Lookup fields.

Instead, you can use the getSearchRecordsByPDC method which is already implemented in this lib.
https://www.zoho.com/crm/help/api/getsearchrecordsbypdc.html#Search_records_using_custom_lookup_fields
