### ISSUE TITLE
Base URL to config

### ISSUE THREAD

**Issue by MixMe** [cristianpontes/zoho-crm-client-php#13]
Move please base url to config, we are from Europe we use https://crm.zoho.eu

From ZohoCRMClient.php from vendor we need to make changes from :
"https://crm.zoho.com/crm/private/xml/"
to
"https://crm.zoho.eu/crm/private/xml/"

**Comment by filnko** [comment]
I stumbled onto the same problem and submitted pull request #15

**Comment by Lykegenes** [comment]
You can specify the domain as the third parameter when instantiating the ZohoCRMClient like this:

```
$client = new ZohoCRMClient('Leads', 'yourAuthToken', 'eu');
```

**Comment by cristianpontes** [comment]
As @Lykegenes  said, you can pass the domain as the third parameter. Please, refer to the new release (1.6)

**Comment by cristianpontes** [comment]
#15
