### ISSUE TITLE
Update Related Records

### ISSUE THREAD

**Issue by arieltoledo** [cristianpontes/zoho-crm-client-php#14]
Hi Cristian, great API, saves me like 1000 of hs of work .
I wonder if there's way to Add Related Records when inserting a new record. 
I have associated the Products modules to my Leads. I have a web form on my site that process the request and creates the Leads, but I need to associate the product aswell. 
Products ara already created in Zoho. 
Zoho api af some docs about it here https://www.zoho.com/crm/help/api/updaterelatedrecords.html.

Thanks in advance.

**Comment by pikulsky** [comment]
@arieltoledo Have you checked https://cristianpontes.github.io/zoho-crm-client-php/#insertRecords, this part:

> In some cases you will need to use more complex data in your records, I.E: In the SalesOrders module, if you want to add some products to your record, pass the 'Product Details' array will be necessary

**Comment by arieltoledo** [comment]
@pikulsky Yes, chekced it out, still trying to make it work.

**Comment by jmcmaster** [comment]
@arieltoledo Did you get this to work?

I'm currently trying to add related products to a Lead when creating the record, but not having success.

**Comment by cristianpontes** [comment]
Hey.

The UpdateRelatedRecords is not implemented at the moment, that would the solution to your case. 

I will implement this method over the weekend.

**Comment by arieltoledo** [comment]
@jmcmaster  Did it by hand creating the xml after the lead is created but the complete process takes too long to response and kill our UX as the form keeps loading, still didn't debug if it is the Zoho api or just my process. @cristianpontes Great news ! It'll come in handy.

**Comment by cristianpontes** [comment]
The implementation for the method "updateRelatedRecords" has been created. Please refer to the new release (1.6). 

https://cristianpontes.github.io/zoho-crm-client-php/#updateRelatedRecords
