### ISSUE TITLE
Support for Zoho Desk

### ISSUE THREAD

**Issue by gblair** [cristianpontes/zoho-crm-client-php#18]
This library has been great so far for integrating with the CRM. Zoho has a pretty similar (although not as robust) API for their Desk product, and I'm now needing to integrate with that API, as well. @cristianpontes, I'm curious if you're open to expanding this particular library to support the Zoho Desk API, in addition to the CRM one. 

In a nutshell, I'm going to dive into the work, and I wanted to see if you are interested in having it integrated with what you've got here, or if I should create a new library based on this one. Because of the overlap of much of the legwork/logic associated with posting to either of these Zoho APIs, I would lean towards adding support to _this_ library -- or breaking out some of this one into small support libraries to keep things DRY -- rather than building a separate library entirely for the Desk API.

If you're into it, I'll be happy to keep a fork of this repo and submit PRs back here once as I get the Desk integration features working. It will likely mean a little bit of refactoring.

What do you think?

**Comment by cristianpontes** [comment]
Hi, @gblair

I have been checking the Zoho Desk API and as you say, it is quite similar to the CRM one. I think it would be a good idea to integrate it and keep improving the lib. 

I have added you as a collaborator in the repo, feel free to create a new branch for this integration.

**Comment by gblair** [comment]
Thanks @cristianpontes! I'll follow up with my changes.
