### ISSUE TITLE
Fata error uploading file 1.26M

### ISSUE THREAD

**Issue by flashnet69** [cristianpontes/zoho-crm-client-php#19]
Great work with this library !!

I'm uploading a file 1.26Mo with the following code :

`$objZohoAccounts = new ZohoCRMClient('Accounts', $this->zoho_apikey);
$objZohoAccounts->uploadFile()->id($intAccountId)->uploadFromPath($strFilePath)->request();`

I have the following error : 

`Fatal error: Uncaught exception 'Buzz\Exception\RequestException' with message 'Operation timed out after 5000 milliseconds with 0 bytes received' in /home/www/fr.mydomain.dev/wptest/wp-content/plugins/fve-tunnel/classes/FVE/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php:29 
Stack trace: #0 /home/www/fr.mydomain.dev/wptest/wp-content/plugins/fve-tunnel/classes/FVE/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(139): Buzz\Client\Curl->send(Object(Buzz\Message\Form\FormRequest), Object(Buzz\Message\Response)) 
#1 /home/www/fr.mydomain.dev/wptest/wp-content/plugins/fve-tunnel/classes/FVE/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(118): Buzz\Browser->send(Object(Buzz\Message\Form\FormRequest)) 
#2 /home/www/fr.mydomain.dev/wptest/wp-content/plugins/fve-tunnel/classes/FVE/vendor/cristianpontes/zoho-crm-client-php/CristianPontes/ZohoCRMClient/Transport/BuzzTransport.php(60): Buzz\Browser->submit('https://crm.zoh...', Array, 'POST', Array) 
#3 /home/www/fr.mydomain.dev/wptest/wp-content/plugins/fve-tunnel/classes/FVE/vendor/cristianpo in /home/www/fr.mydomain.dev/wptest/wp-content/plugins/fve-tunnel/classes/FVE/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php on line 29`

My file is uploaded but how to increase the timeout? Thanks for you help

**Comment by cristianpontes** [comment]
Hello, @flashnet69 

Thanks!

Sometimes, Zoho takes a while to return a response in that kind of requests. 

You can increase the timeout in the constructor, like this:

```php
$client =  new ZohoCRMClient('Accounts', 'AuthToken', 'com', 10); 
```

Where the 3rd parameter is the domain (com or eu) and the 4th parameter is the timeout (in seconds)

**Comment by flashnet69** [comment]
It works well, thanks for your help
