### ISSUE TITLE
SearchRecords orWhere does not allow same fields

### ISSUE THREAD

**Issue by pikulsky** [cristianpontes/zoho-crm-client-php#2]
While using orWhere it's logical to check same field with different values.
Zoho does allow to search the same fields. It has no meaning for where(), but it's OK for orWhere.
https://www.zoho.com/crm/help/api/searchrecords.html
In "Notes" section:
> You can use a maximum of 5 criteria (with same or different columns) with equals and startsWith conditions

```
$client = new ZohoCRMClient('Accounts', self::AUTH_TOKEN);
$request = $client->searchRecords();
$request->where('field1', 'value1');
$emails = array('email1', 'email2', 'email3');
foreach ($emails as $email) {
    $request->orWhere('E-mail', $email);
}
$records = $request->request();
```

Now only the last of orWhere() values for the same field is kept.

**Comment by cristianpontes** [comment]
I'll check the documentation and do the update

**Comment by cristianpontes** [comment]
Thanks for the pull request. I didn't have time.
