### ISSUE TITLE
Catch error not working 

### ISSUE THREAD

**Issue by JosephMendez** [cristianpontes/zoho-crm-client-php#20]
instead of showing this error , there is a way to catch error 

in XmlDataTransportDecorator.php (line 195)
--
at XmlDataTransportDecorator->parse('<?xml version="1.0" encoding="UTF-8" ?><response uri="/crm/private/xml/Leads/searchRecords"><nodata><code>4422</code><message>There is no data to show</message></nodata></response>')in XmlDataTransportDecorator.php (line 54)

**Comment by pikulsky** [comment]
@JosephMendez could you please explain more: what is actual behavior, what you expect.
Maybe, with a snippet of your code if possible.
Or maybe suggest a pull request for your issue?

**Comment by JosephMendez** [comment]
Hi pikulsky,

sorry, i am asking if there is a way to catch this error. 

in XmlDataTransportDecorator.php (line 195)
at XmlDataTransportDecorator->parse('4422There is no data to show')in XmlDataTransportDecorator.php (line 54);

**Comment by JosephMendez** [comment]
@pikulsky  please any ideas?

**Comment by JosephMendez** [comment]
can we change to 


`  $xml = new SimpleXMLElement($content);
        if (isset($xml->error)) {
          /*  throw new Exception\ZohoErrorException(
                new ZohoError(
                    (string) $xml->error->code,
                    (string) $xml->error->message
                )
            ); */
          return 'error';
        }

        if (isset($xml->nodata)) {
            /*throw new Exception\NoDataException(
                new ZohoError(
                    (string)$xml->nodata->code, (string) $xml->nodata->message
                )
            ); */
          return 'nodata';
        }
`

**Comment by pikulsky** [comment]
> can we change
@JosephMendez , there is no advantages of the suggested change. instead of catching NoDataException to know there no more data, you will compare return with 'nodata'  string..
I do this way:
```
        try {
            $request = $client->getRecords()
                ->fromIndex($fromIndex)
                ->toIndex($toIndex)
                ->request();
        } catch (NoDataException $ex) {
            // no data, do nothing
        }
```
Is it OK for you?

**Comment by cristianpontes** [comment]
This project is no longer maintained and has been deprecated in favor of the official Zoho PHP SDK. 

For more information, please visit [Zoho's official documentation](https://www.zoho.com/crm/developer/docs/server-side-sdks/php.html)

I want to thank you for using the project and my sincere apologies for any inconveniences

Sincerely,
Cristian
