### ISSUE TITLE
Creating notes

### ISSUE THREAD

**Issue by nostalgicdodo** [cristianpontes/zoho-crm-client-php#21]
hey,

Is it possible to create notes with this library? I couldn't find anything about it in the docs.

**Comment by cristianpontes** [comment]
This project is no longer maintained and has been deprecated in favor of the official Zoho PHP SDK. 

For more information, please visit [Zoho's official documentation](https://www.zoho.com/crm/developer/docs/server-side-sdks/php.html)

I want to thank you for using the project and my sincere apologies for any inconveniences

Sincerely,
Cristian
