### ISSUE TITLE
onDuplicateUpdate function

### ISSUE THREAD

**Issue by ratskin** [cristianpontes/zoho-crm-client-php#22]
I've been testing inserting contacts. I'd like to have the functionality to create new contacts, or update existing ones if their email address matches. It seems this functionality is already implemented (yay!), but I just want to confirm it's doing what I think it is.

I have this code, that I expect to operate thusly; try to insert a new user ("John", "Doe", "john.doe@example.com"), except if user exists (based only on email address), then update existing user with new info.
```
$client = new ZohoCRMClient('Contacts', getenv('AUTHTOKEN'), 'eu');
$records = $client->insertRecords()->setRecords([array(
	'First Name' => "John",
	'Last Name' => "Doe",
	'Email' => "john.doe@example.com"
)])->onDuplicateUpdate()->triggerWorkflow()->request();
```

On an additional side note, I'm wondering what the triggerWorkflow function does. Your documentation says "Trigger the workflow rule while inserting record.", I'm just wondering what the "workflow rule" is.

**Comment by danielmulder** [comment]
Hi,

A similar thing happened to me to and I fixed it. When working with the Insert example you need to change the fieldname email to Email with a capital E. 

`          array(
              'First Name' => 'John',
              'Last Name' => 'Doe',
              'Email' => 'johndoe@gmail.com',
          )`
Now you will notice that the new records have a email inserted and now also the check works.

Hope this helps.

Gr

**Comment by ratskin** [comment]
Thanks, I actually solved this a while ago
