### ISSUE TITLE
Operation timed out after 5007 milliseconds with 1263463414366208 bytes received

### ISSUE THREAD

**Issue by ahkhan696** [cristianpontes/zoho-crm-client-php#23]
I want to download attachments from leads. but I face the following error. can you help me please?

Fatal error:  Uncaught Buzz\Exception\RequestException: Operation timed out after 5007 milliseconds with 1263463414366208 bytes received in C:\xampp\htdocs\testprojects\vendor\kriswallsmith\buzz\lib\Buzz\Client\Curl.php:29
Stack trace:
#0 C:\xampp\htdocs\testprojects\vendor\kriswallsmith\buzz\lib\Buzz\Browser.php(139): Buzz\Client\Curl->send(Object(Buzz\Message\Request), Object(Buzz\Message\Response))
#1 C:\xampp\htdocs\testprojects\vendor\kriswallsmith\buzz\lib\Buzz\Browser.php(91): Buzz\Browser->send(Object(Buzz\Message\Request))
#2 C:\xampp\htdocs\testprojects\vendor\kriswallsmith\buzz\lib\Buzz\Browser.php(45): Buzz\Browser->call(Object(Buzz\Util\Url), 'POST', Array, 'id=285706000000...')
#3 C:\xampp\htdocs\testprojects\vendor\cristianpontes\zoho-crm-client-php\CristianPontes\ZohoCRMClient\Transport\BuzzTransport.php(64): Buzz\Browser->post('https://crm.zoh...', Array, 'id=285706000000...')
#4 C:\xampp\htdocs\testprojects\vendor\cristianpontes\zoho-crm-client-php\CristianPontes\ZohoCRMClient\Transport\AuthenticationToke in C:\xampp\htdocs\testprojects\vendor\kriswallsmith\buzz\lib\Buzz\Client\Curl.php on line 29

**Comment by pikulsky** [comment]
First, try to increase the timeout value. something like this:
Instead of:
```
$client = new ZohoCRMClient('Leads', 'YourAuthToken');
```
do this:
```
    /**
     * The default timeout 5 sec is not enough, 30 is OK
     */
    const ZOHO_CALL_TIMEOUT_SECONDS = 30;
...
        $curl_client = new \Buzz\Client\Curl();
        // set custom timeout
        $curl_client->setTimeout(self::ZOHO_CALL_TIMEOUT_SECONDS);

        $buzzTransport = new BuzzTransport(
            new \Buzz\Browser($curl_client), // and then pass it in here
            'https://crm.zoho.com/crm/private/xml/'
        );

        $transport = new XmlDataTransportDecorator(
            new AuthenticationTokenTransportDecorator(
                'YourAuthToken',
                $buzzTransport
            )
        );
        $client = new ZohoCRMClient('Leads', $transport);
```

**Comment by pikulsky** [comment]
@cristianpontes do you you think it's ok to refactor ZohoCRMClient to make it more easy to set a custom timeout?  The default timeout is not enough.
Or just add a note in readme with the code above?

**Comment by cristianpontes** [comment]
This project is no longer maintained and has been deprecated in favor of the official Zoho PHP SDK. 

For more information, please visit [Zoho's official documentation](https://www.zoho.com/crm/developer/docs/server-side-sdks/php.html)

I want to thank you for using the project and my sincere apologies for any inconveniences

Sincerely,
Cristian
