### ISSUE TITLE
Disable SSL

### ISSUE THREAD

**Issue by AlonsoK28** [cristianpontes/zoho-crm-client-php#26]
How I can **disable** SSL connection _for Develop enviroments test_?

Greetings.

**Comment by pikulsky** [comment]
SSL to connection to where? Tests do not make any connections, transport is mocked.
Could you please explain your case?

**Comment by AlonsoK28** [comment]
I am behind a firewall a getting a HTTPS connection to connect with Zoho WS is imposible from my develop enviroment. 

I need to set the next lines in order to **zoho-crm-client-php** works because if not server response was **SSLcertificate problem: unable to get local issuer certificate**.

AbstractCurl.php
` 272. curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);`
` 273. curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);`

Greetings.

**Comment by pikulsky** [comment]
google for "php curl SSLcertificate problem: unable to get local issuer certificate"
try this: https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate
