### ISSUE TITLE
Use of Custom Fields

### ISSUE THREAD

**Issue by AlonsoK28** [cristianpontes/zoho-crm-client-php#27]
How I can use Custom fields with your API?

**Can you document some examples?**

Greetings.

**Comment by pikulsky** [comment]
Custom fields are used same way as built-in fields. No difference.

**Comment by AlonsoK28** [comment]
Maybe you could document with a little more detail how to get "labels" of Custom fields from ZOHO CRM API portal.

**Comment by pikulsky** [comment]
There is getFields API call (https://www.zoho.com/crm/help/api/getfields.html) to get all fields including custom ones. Same way custom module's fields can be retrieved, where the module name should be like CustomModuleN:
for build-in module, e.g. Tasks:
https://crm.zoho.com/crm/private/xml/Tasks/getFields?authtoken=Auth Token&scope=crmapi
for custom module, e.g. CustomModule1
https://crm.zoho.com/crm/private/xml/CustomModule1/getFields?authtoken=Auth Token&scope=crmapi
