### ISSUE TITLE
How can I delete a row using updateRecords ?

### ISSUE THREAD

**Issue by ZHB** [cristianpontes/zoho-crm-client-php#29]
Hello,

How can I use updateRecords method to delete a product row in product details ?

I have an array like this an I whant to update the record to remove  product 10002 : 
```
'...' => ...,
'Product Details' => [
    [
        [Product Id] => 10001
        [Quantity] => 1
        [Unit Price] => 10.00
        [List Price] => 10.00
        [Total] => 10.00
        [Net Total] => 10.00
    ],
    [
        [Product Id] => 10002
        [Quantity] => 1
        [Unit Price] => 10.00
        [List Price] => 10.00
        [Total] => 10.00
        [Net Total] => 10.00
    ],
],
'...' => ...,
```

Thank you for your answers

**Comment by cristianpontes** [comment]
This project is no longer maintained and has been deprecated in favor of the official Zoho PHP SDK. 

For more information, please visit [Zoho's official documentation](https://www.zoho.com/crm/developer/docs/server-side-sdks/php.html)

I want to thank you for using the project and my sincere apologies for any inconveniences

Sincerely,
Cristian
