### ISSUE TITLE
Call to undefined method Buzz\Client\Curl::setTimeout()

### ISSUE THREAD

**Issue by xaniuskarlhall** [cristianpontes/zoho-crm-client-php#30]
I have added this package over  a month now  and it was working fine. However, I am getting a error undefined method Buzz\Client\Curl::setTimeout() error. How can this issue be resolved

**Comment by pikulsky** [comment]
@xaniuskarlhall  see #23

**Comment by delameko** [comment]
Hi xaniuskarlhall,

I had the same issue.  It appears that version 17 of Buzz removes the setTimeout function, hence the error.

I found the easiest way to solve it was to add Buzz directly to my project and limit it to version 16.

    composer require kriswallsmith/buzz:^0.16

**Comment by cristianpontes** [comment]
Fixed
