### ISSUE TITLE
Duplicate record Last Name

### ISSUE THREAD

**Issue by AlonsoK28** [cristianpontes/zoho-crm-client-php#32]
In case that the record Last Name is duplicated, how can I call insertRecords again to modify the "Last Name"?

EXAMPLE:
1st try
"Jonh Doe" >> Duplicated

2nd try
"Jonh Doe" + "1" >> Inserted

Greetings

**Comment by cristianpontes** [comment]
This project is no longer maintained and has been deprecated in favor of the official Zoho PHP SDK. 

For more information, please visit [Zoho's official documentation](https://www.zoho.com/crm/developer/docs/server-side-sdks/php.html)

I want to thank you for using the project and my sincere apologies for any inconveniences

Sincerely,
Cristian
