### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by erdemnagikho** [cristianpontes/zoho-crm-client-php#40]
Hi, i am getting this error ' - Installation request for cristianpontes/zoho-crm-client-php ^1.7 -> satisfiable by cristianpontes/zoho-crm-client-php[1.7].' when i want to install package composer require cristianpontes/zoho-crm-client-php.

**Comment by maxvet** [comment]
Same thing here :-(

**Comment by cristianpontes** [comment]
This project is no longer maintained and has been deprecated in favor of the official Zoho PHP SDK. 

For more information, please visit [Zoho's official documentation](https://www.zoho.com/crm/developer/docs/server-side-sdks/php.html)

I want to thank you for using the project and my sincere apologies for any inconveniences

Sincerely,
Cristian
