### ISSUE TITLE
I have facing issue to google pagespeed insights. 

### ISSUE THREAD

**Issue by ahkhan696** [cristianpontes/zoho-crm-client-php#41]
I want to understand this question mark showing as result.
![image](https://user-images.githubusercontent.com/16847283/66823107-fcdfcb00-ef5e-11e9-8726-43f7c315b13e.png)

**Comment by cristianpontes** [comment]
This project is no longer maintained and has been deprecated in favour of the official Zoho PHP SDK. 

For more information, please visit [Zoho's official's documentation](https://www.zoho.com/crm/developer/docs/server-side-sdks/php.html)

Thanks a lot of using the project and apologies for any inconvenience. 

Sincerely,
Cristian

**Comment by cristianpontes** [comment]
This project is no longer maintained and has been deprecated in favor of the official Zoho PHP SDK. 

For more information, please visit [Zoho's official documentation](https://www.zoho.com/crm/developer/docs/server-side-sdks/php.html)

I want to thank you for using the project and my sincere apologies for any inconveniences

Sincerely,
Cristian
